Adjust and export interfaces
selsa-inube/inubekit-breadcrumbs pull request #11
Opened 2024-03-21 20:17 UTC by JanuarAsprilla

The names of the interfaces used by the `<Breadcrumbs />` component were refactored, as well as how they are exported.

2024-03-27 15:51 UTC, wfercanas requested changes

2024-03-27 15:51 UTC, wfercanas commented on src/Breadcrumbs/BreadcrumbLink/props.ts
> +type IBreadcrumbLinkSizes = "large" | "small";
Refactor to use an array to store sizes. Then create te interface (not type) `IBreadcrumbLinkSize` with `(typeof sizes)[number]`

2024-03-27 15:51 UTC, wfercanas commented on src/Breadcrumbs/props.ts
> +type IBreadcrumbsSizes = (typeof sizes)[number];
Rename to `IBreadcrumbsSize`

2024-03-27 15:51 UTC, wfercanas commented on src/Breadcrumbs/props.ts
> +interface IBreadcrumbsIRoute {
Rename to `IBreadcrumbsRoute`

2024-03-27 15:51 UTC, wfercanas commented on src/index.ts
> +export type { IBreadcrumbs } from "./Breadcrumbs/index";
In shouldn't be necessary to add `/index` in the path. Remove it and execute `npm run build` to check if the type is exported in d.ts file

2024-03-27 15:52 UTC, wfercanas commented on src/index.ts
> +export type { IBreadcrumbs } from "./Breadcrumbs/index";
Actually, the build has some problems:

![image](https://github.com/selsa-inube/inubekit-breadcrumbs/assets/36939686/5e18ff30-a17e-440c-89c4-46bf7554bbe7)

2024-03-29 21:38 UTC, JanuarAsprilla commented on src/Breadcrumbs/BreadcrumbLink/props.ts
> +type IBreadcrumbLinkSizes = "large" | "small";
solved

2024-03-29 21:42 UTC, JanuarAsprilla commented on src/Breadcrumbs/props.ts
> +type IBreadcrumbsSizes = (typeof sizes)[number];
solved

2024-03-29 21:44 UTC, JanuarAsprilla commented on src/Breadcrumbs/props.ts
> +interface IBreadcrumbsIRoute {
solved

2024-03-29 21:53 UTC, JanuarAsprilla commented on src/index.ts
> +export type { IBreadcrumbs } from "./Breadcrumbs/index";
solved

2024-04-01 15:49 UTC, wfercanas approved these changes

2024-04-01 15:49 UTC, merged