Refactor components to use new token structure
selsa-inube/inubekit-breadcrumbs pull request #8
Opened 2024-03-12 16:36 UTC by cmarin001

This pull request details the refactoring of the `<Breadcrumbs/>` component within our application, aiming to integrate it with the newly adopted design token structure. This initiative is geared towards enhancing the component's consistency with the updated design system, improving its maintainability, and ensuring a seamless user experience by leveraging the advanced capabilities provided by the new tokens.

2024-03-12 20:22 UTC, JanuarAsprilla approved these changes

2024-03-13 16:39 UTC, wfercanas requested changes

2024-03-13 21:02 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbLink/props.ts
> +type Appearance = (typeof appearances)[number];
solved

2024-03-13 21:02 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbLink/props.ts
>  type Sizes = "large" | "medium" | "small";
solved

2024-03-13 21:20 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbLink/styles.js
> +      inube.text.gray.content.color.regular};
solved

2024-03-13 21:22 UTC, cmarin001 commented on src/index.ts
>  export { BreadcrumbLink } from "./Breadcrumbs/BreadcrumbLink";
solved

2024-03-13 21:31 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbMenu/styles.js
> +        inube.text.light.content.color.disabled
solved

2024-03-13 21:37 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbMenu/styles.js
> +  border-radius: 4px;
solved

2024-03-13 21:41 UTC, cmarin001 commented on src/Breadcrumbs/index.tsx
> +          }
solved

2024-03-13 21:41 UTC, cmarin001 commented on src/Breadcrumbs/index.tsx
> +          appearance={inube.breadcrumbs.content.appearance.active as Appearance}
solved

2024-03-13 21:47 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbMenu/styles.js
> +        inube.text.light.content.color.regular};
solved

2024-03-13 21:47 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbMenuLink/styles.js
>      > label {
solved

2024-03-13 21:56 UTC, cmarin001 commented on src/Breadcrumbs/styles.js
>      content: "/";
solved

2024-03-14 17:34 UTC, wfercanas commented on src/Breadcrumbs/BreadcrumbMenu/styles.js
> +        inube.text.light.content.color.disabled
In figma we're using a different token. Adjust:
![image](https://github.com/selsa-inube/inubekit-breadcrumbs/assets/36939686/b443232a-fccb-4cc0-a2fd-ea1c7d39ba30)

2024-03-14 17:36 UTC, wfercanas commented on src/Breadcrumbs/BreadcrumbLink/styles.js
> +      inube.text.gray.content.color.regular};
We're passing `$active` to `StyledBreadcrumbLink`, but currently we're not using that prop in the styled component.
Use that prop so that the text-decoration-color of this link uses the text token that matches with the `$active` prop value.

The idea is that the underline color equals the color of the text.

2024-03-14 17:48 UTC, wfercanas requested changes

2024-03-14 17:48 UTC, wfercanas commented on src/Breadcrumbs/BreadcrumbMenuLink/styles.js
>      height: 32px;
This `height` is not necessary and causes that you must add a Stack in index.tsx to avoid this height to apply.

Delete this `height` and also the Stack in index.tsx.

2024-03-14 17:48 UTC, wfercanas commented on src/Breadcrumbs/BreadcrumbEllipsis/styles.js
> +      theme?.palette?.neutral?.N300 || inube.palette.neutral.N300};
Since we're using text with appearance prop equal to "gray", we can as well use that token here.

This help us avoid that in the future, for some themes, neutral.n300 is not the same value for the gray texts and visually we get to see a mismatch.

2024-03-14 19:55 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbLink/styles.js
> +      inube.text.gray.content.color.regular};
solved

2024-03-14 20:12 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbMenu/styles.js
> +        inube.text.light.content.color.disabled
solved

2024-03-14 20:15 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbEllipsis/styles.js
> +      theme?.palette?.neutral?.N300 || inube.palette.neutral.N300};
solved

2024-03-14 20:17 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbMenuLink/styles.js
>      height: 32px;
solved

2024-03-15 16:01 UTC, cmarin001 commented on src/Breadcrumbs/BreadcrumbLink/styles.js
> +      inube.text.gray.content.color.regular};
solved

2024-03-15 21:37 UTC, JanuarAsprilla approved these changes

2024-03-18 20:43 UTC, wfercanas approved these changes

2024-03-18 20:43 UTC, merged